### ISSUE TITLE
cloning in new desktop

### ISSUE THREAD

**Issue by vivkay** [vivkay/exercise-2-scss#1]
Hey @thomasjbradley, 

I'm having problems with prepros so I'm trying to do our current assignment on another computer, but I can't seem to get the repository to connect to github on this other computer (I downloaded the files as a zip from github, and then opened the github app – like we usually do when we're setting it up). Do you have any ideas?

Thanks so much for your help. I'm considering just not doing this assignment, which is sad, simply because I can't get the software to work :(

**Comment by thomasjbradley** [comment]
When you download it as a zip it's no longer a GitHub repository.
You'll need to Clone it to your new computer too.

**Comment by vivkay** [comment]
okie dokie! Thanks Thomas.

**Comment by vivkay** [comment]
@thomasjbradley just wanted to say I found another way! I scoured the web and found that Koala is open source and better for my computer than Prepros! There shall be no scss defeats today! yay!! :dragon:
